# Generated by Django 5.2 on 2026-02-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="llm_latency_ms",
            field=models.IntegerField(
                default=0, help_text="LLM generation time in milliseconds"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="rag_latency_ms",
            field=models.IntegerField(
                default=0, help_text="RAG search time in milliseconds"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="top_rag_score",
            field=models.FloatField(
                default=0.0, help_text="Highest RAG similarity score for this response"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="total_latency_ms",
            field=models.IntegerField(
                default=0, help_text="Total response time in milliseconds"
            ),
        ),
    ]
