# Generated by Django 5.2 on 2026-03-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatmessage_llm_latency_ms_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="feedback",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="rating",
            field=models.IntegerField(
                blank=True,
                help_text="User rating from 1 to 5 stars (null = no rating)",
                null=True,
            ),
        ),
    ]
