# Generated by Django 5.2 on 2026-04-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_rating_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="llm_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="LLM model used for generation",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="llm_prompt_tokens",
            field=models.IntegerField(
                default=0, help_text="Number of prompt tokens sent to LLM"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="llm_response_tokens",
            field=models.IntegerField(
                default=0, help_text="Number of tokens generated by LLM"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="llm_tokens_per_second",
            field=models.FloatField(
                default=0.0, help_text="LLM generation throughput (tokens/sec)"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="rag_num_sources",
            field=models.IntegerField(
                default=0, help_text="Number of RAG sources retrieved"
            ),
        ),
    ]
